// ══════════════════════════════════════════════════════════════
// PDF EXPORT — Generate analysis report using jsPDF
// Single page per thumbnail, compact structured layout
// ══════════════════════════════════════════════════════════════

import { jsPDF } from 'jspdf';

const COLORS = {
  dark: [20, 20, 19],
  muted: [107, 114, 128],
  orange: [217, 119, 87],
  green: [16, 185, 129],
  yellow: [180, 140, 8],
  red: [239, 68, 68],
  blue: [106, 155, 204],
  white: [255, 255, 255],
  lightBg: [250, 249, 245],
  divider: [220, 218, 210]
};

function getVerdictColor(verdict) {
  if (verdict === 'PUBLISH') return COLORS.green;
  if (verdict === 'REVISE') return COLORS.yellow;
  return COLORS.red;
}

// Strip non-ASCII characters that jsPDF can't render (Hindi, emojis, special symbols)
// Replace common Unicode with ASCII equivalents
function sanitize(text) {
  if (!text) return '';
  return String(text)
    .replace(/₹/g, 'Rs.')
    .replace(/[✓✔]/g, 'YES')
    .replace(/[✗✘]/g, 'NO')
    .replace(/≤/g, '<=')
    .replace(/≥/g, '>=')
    .replace(/•/g, '-')
    .replace(/—/g, '--')
    .replace(/–/g, '-')
    .replace(/[""]/g, '"')
    .replace(/['']/g, "'")
    .replace(/…/g, '...')
    // Remove any remaining non-ASCII characters
    .replace(/[^\x20-\x7E\n\r\t]/g, '')
    .trim();
}

// Truncate text to fit within a max number of lines
function fitText(doc, text, maxWidth, maxLines) {
  if (!text) return [];
  const clean = sanitize(text);
  if (!clean) return [];
  const lines = doc.splitTextToSize(clean, maxWidth);
  if (lines.length > maxLines) {
    const truncated = lines.slice(0, maxLines);
    const last = truncated[maxLines - 1];
    truncated[maxLines - 1] = last.length > 3 ? last.slice(0, -3) + '...' : last;
    return truncated;
  }
  return lines;
}

export function generateReport(analyses, userInfo) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageW = 210;
  const pageH = 297;
  const m = 15;
  const cW = pageW - m * 2;
  const lineH = 3.5;
  const colGap = 8;
  const leftColW = 82;
  const rightColW = cW - leftColW - colGap;

  // ── Cover Page ──
  doc.setFillColor(...COLORS.dark);
  doc.rect(0, 0, pageW, pageH, 'F');

  doc.setTextColor(...COLORS.orange);
  doc.setFontSize(32);
  doc.text('Thumbnail Analysis', m, 85);
  doc.setFontSize(20);
  doc.text('Report', m, 97);

  doc.setTextColor(...COLORS.white);
  doc.setFontSize(12);
  const userName = sanitize(userInfo?.user_metadata?.full_name) || 'User';
  doc.text('Prepared for: ' + userName, m, 125);
  doc.text('Date: ' + new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }), m, 136);
  doc.text('Total Analyses: ' + analyses.length, m, 147);

  if (analyses.length > 0) {
    const scores = analyses.map(a => a.total_score);
    const avg = Math.round(scores.reduce((a, b) => a + b, 0) / scores.length);
    const best = Math.max(...scores);
    const publishCount = analyses.filter(a => a.verdict === 'PUBLISH').length;
    doc.setTextColor(...COLORS.muted);
    doc.setFontSize(10);
    doc.text('Average Score: ' + avg + '/100   |   Best Score: ' + best + '/100   |   Publish-ready: ' + publishCount + '/' + analyses.length, m, 162);
  }

  doc.setTextColor(...COLORS.muted);
  doc.setFontSize(8);
  doc.text('Generated by Thumbnail Analyzer', m, pageH - 15);

  // ── Analysis Pages — one per thumbnail ──
  for (let i = 0; i < analyses.length; i++) {
    const a = analyses[i];
    const analysis = a.analysis || {};
    doc.addPage();

    // ── Top header bar ──
    doc.setFillColor(...COLORS.dark);
    doc.rect(0, 0, pageW, 12, 'F');
    doc.setTextColor(...COLORS.orange);
    doc.setFontSize(8);
    doc.text('Analysis ' + (i + 1) + ' of ' + analyses.length, m, 8);
    doc.setTextColor(...COLORS.muted);
    const dateStr = a.created_at
      ? new Date(a.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
      : '';
    doc.text(dateStr, pageW - m, 8, { align: 'right' });

    let y = 18;

    // ── Title ──
    doc.setTextColor(...COLORS.dark);
    doc.setFontSize(14);
    const titleLines = fitText(doc, a.title || 'Untitled', cW, 2);
    doc.text(titleLines, m, y);
    y += titleLines.length * 6 + 1;

    // ── Category + Content Type ──
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.orange);
    const catText = sanitize(a.category) || '';
    doc.text(catText, m, y);
    if (a.content_type) {
      doc.setTextColor(...COLORS.blue);
      const ctText = sanitize(a.content_type);
      doc.text('  |  ' + ctText, m + doc.getTextWidth(catText) + 2, y);
    }
    y += 6;

    // ── Divider ──
    doc.setDrawColor(...COLORS.divider);
    doc.setLineWidth(0.3);
    doc.line(m, y, pageW - m, y);
    y += 4;

    // ══ TWO-COLUMN: Left = Thumbnail + Score, Right = Checklist + Info ══
    const twoColTop = y;

    // ── LEFT COLUMN ──
    let leftY = twoColTop;

    // Thumbnail image
    const thumbW = leftColW;
    const thumbH = 45;
    if (a.image_base64 && a.image_base64.length > 100) {
      try {
        // Try PNG first, fall back to JPEG
        let format = 'JPEG';
        let dataUri = 'data:image/jpeg;base64,' + a.image_base64;
        if (a.image_base64.startsWith('iVBOR')) {
          format = 'PNG';
          dataUri = 'data:image/png;base64,' + a.image_base64;
        }
        doc.addImage(dataUri, format, m, leftY, thumbW, thumbH);
        leftY += thumbH + 4;
      } catch {
        leftY += 2;
      }
    }

    // Score + Verdict
    doc.setFontSize(22);
    const verdictColor = getVerdictColor(a.verdict);
    doc.setTextColor(...verdictColor);
    const scoreStr = String(a.total_score);
    doc.text(scoreStr, m, leftY + 2);
    const scoreTextW = doc.getTextWidth(scoreStr);
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.muted);
    doc.text('/100', m + scoreTextW + 1, leftY + 2);

    doc.setFontSize(11);
    doc.setTextColor(...verdictColor);
    doc.text(a.verdict || '', m + scoreTextW + 16, leftY + 2);
    leftY += 8;

    // Score breakdown
    doc.setFontSize(7.5);
    doc.setTextColor(...COLORS.dark);
    doc.text('Design: ' + (a.design_score || 0) + '/75', m, leftY);
    doc.text('Category Fit: ' + (a.cat_score >= 0 ? '+' : '') + (a.cat_score || 0) + '/25', m + 35, leftY);
    leftY += 6;

    // ── RIGHT COLUMN ──
    const rightX = m + leftColW + colGap;
    let rightY = twoColTop;

    // Design Checklist heading
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.orange);
    doc.setFont(undefined, 'bold');
    doc.text('Design Checklist', rightX, rightY);
    doc.setFont(undefined, 'normal');
    rightY += 5;

    const checks = [
      ['Text Readable', analysis.text_readable],
      ['High Contrast', analysis.high_contrast],
      ['Bold Font', analysis.bold_font],
      ['Clean Layout', analysis.clean_layout],
      ['Word Count <=7', analysis.word_count_ok],
      ['Face Visible', analysis.face_visible],
      ['Hindi Text', analysis.hindi_text]
    ];

    // Render checklist as two-column grid with colored YES/NO
    doc.setFontSize(7);
    const checkColW = rightColW / 2;
    let checkIdx = 0;
    for (let ci = 0; ci < checks.length; ci++) {
      const [label, val] = checks[ci];
      if (val === undefined) continue;
      const col = checkIdx % 2;
      const cx = rightX + col * checkColW;

      // Draw colored dot
      const dotColor = val ? COLORS.green : COLORS.red;
      doc.setFillColor(...dotColor);
      doc.circle(cx + 1.2, rightY - 1, 1, 'F');

      // Label text
      doc.setTextColor(...COLORS.dark);
      doc.text(label, cx + 4, rightY);

      if (col === 1) rightY += 4.5;
      checkIdx++;
    }
    if (checkIdx % 2 === 1) rightY += 4.5;
    rightY += 3;

    // Detected Text
    if (analysis.text_on_thumbnail) {
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.orange);
      doc.setFont(undefined, 'bold');
      doc.text('Detected Text', rightX, rightY);
      doc.setFont(undefined, 'normal');
      rightY += 4;
      doc.setFontSize(7);
      doc.setTextColor(...COLORS.dark);
      const dtLines = fitText(doc, analysis.text_on_thumbnail, rightColW, 3);
      doc.text(dtLines, rightX, rightY);
      rightY += dtLines.length * lineH + 3;
    }

    // Visual Analysis
    const visualParts = [];
    if (analysis.background_type) visualParts.push('BG: ' + sanitize(analysis.background_type));
    if (analysis.focal_point) visualParts.push('Focal: ' + sanitize(analysis.focal_point));
    if (analysis.text_placement) visualParts.push('Text: ' + sanitize(analysis.text_placement));
    if (analysis.visual_flow) visualParts.push('Flow: ' + sanitize(analysis.visual_flow));
    if (visualParts.length > 0) {
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.orange);
      doc.setFont(undefined, 'bold');
      doc.text('Visual Analysis', rightX, rightY);
      doc.setFont(undefined, 'normal');
      rightY += 4;
      doc.setFontSize(7);
      doc.setTextColor(...COLORS.dark);
      for (const vp of visualParts) {
        const vpLines = fitText(doc, vp, rightColW, 2);
        doc.text(vpLines, rightX, rightY);
        rightY += vpLines.length * lineH + 0.5;
      }
      rightY += 2;
    }

    // Continue below the taller column
    y = Math.max(leftY, rightY) + 3;

    // ── Divider ──
    doc.setDrawColor(...COLORS.divider);
    doc.line(m, y, pageW - m, y);
    y += 4;

    // ══ LOWER SECTIONS — two-column layout ══
    let lowerLeftY = y;
    let lowerRightY = y;
    const lowerLeftX = m;
    const lowerRightX = m + leftColW + colGap;
    const lowerLeftW = leftColW;
    const lowerRightW = rightColW;

    // Helper: add a compact list section
    function addCompactSection(x, startY, width, title, items, maxItemLines) {
      let sy = startY;
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.orange);
      doc.setFont(undefined, 'bold');
      doc.text(title, x, sy);
      doc.setFont(undefined, 'normal');
      sy += 4;
      doc.setFontSize(7);
      doc.setTextColor(...COLORS.dark);
      for (const item of items) {
        const lines = fitText(doc, '- ' + sanitize(item), width - 2, maxItemLines);
        doc.text(lines, x + 1, sy);
        sy += lines.length * lineH + 0.8;
      }
      return sy + 2;
    }

    // Helper: add a compact text section
    function addCompactText(x, startY, width, title, text, maxLines) {
      let sy = startY;
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.orange);
      doc.setFont(undefined, 'bold');
      doc.text(title, x, sy);
      doc.setFont(undefined, 'normal');
      sy += 4;
      doc.setFontSize(7);
      doc.setTextColor(...COLORS.dark);
      const lines = fitText(doc, text, width, maxLines);
      doc.text(lines, x, sy);
      return sy + lines.length * lineH + 3;
    }

    // LEFT LOWER: Category Warnings, Tips, Colors, Scroll-stop
    if (a.cat_warnings && a.cat_warnings.length > 0) {
      lowerLeftY = addCompactSection(lowerLeftX, lowerLeftY, lowerLeftW, 'Category Warnings', a.cat_warnings, 2);
    }
    if (a.cat_tips && a.cat_tips.length > 0) {
      lowerLeftY = addCompactSection(lowerLeftX, lowerLeftY, lowerLeftW, 'Category Tips', a.cat_tips, 2);
    }
    if (analysis.dominant_colors) {
      lowerLeftY = addCompactText(lowerLeftX, lowerLeftY, lowerLeftW, 'Dominant Colors', analysis.dominant_colors, 2);
    }
    if (analysis.scroll_stop_power) {
      lowerLeftY = addCompactText(lowerLeftX, lowerLeftY, lowerLeftW, 'Scroll-Stop Power', analysis.scroll_stop_power, 3);
    }

    // RIGHT LOWER: Design Fixes, Overall Impression
    const fixes = [analysis.design_fix_1, analysis.design_fix_2, analysis.design_fix_3].filter(Boolean);
    if (fixes.length > 0) {
      lowerRightY = addCompactSection(lowerRightX, lowerRightY, lowerRightW, 'Top Design Fixes', fixes, 2);
    }
    if (analysis.overall_impression) {
      lowerRightY = addCompactText(lowerRightX, lowerRightY, lowerRightW, 'Overall Impression', analysis.overall_impression, 4);
    }

    // ── AI Prompt section — full width at bottom ──
    const aiPromptText = analysis.complete_thumbnail_feedback || a.complete_thumbnail_feedback;
    if (aiPromptText) {
      y = Math.max(lowerLeftY, lowerRightY) + 2;

      if (y < pageH - 30) {
        doc.setDrawColor(...COLORS.divider);
        doc.line(m, y, pageW - m, y);
        y += 4;

        doc.setFontSize(8);
        doc.setTextColor(...COLORS.orange);
        doc.setFont(undefined, 'bold');
        doc.text('AI Thumbnail Prompt', m, y);
        doc.setFont(undefined, 'normal');
        y += 4;

        const remainingSpace = pageH - y - 10;
        const maxPromptLines = Math.floor(remainingSpace / lineH);
        doc.setFontSize(6.5);
        doc.setTextColor(...COLORS.dark);
        const promptLines = fitText(doc, aiPromptText, cW, Math.min(maxPromptLines, 14));
        doc.text(promptLines, m, y);
      }
    }

    // ── Page footer ──
    doc.setFontSize(6);
    doc.setTextColor(...COLORS.muted);
    doc.text('Thumbnail Analyzer Report', m, pageH - 6);
    doc.text('Page ' + (i + 2), pageW - m, pageH - 6, { align: 'right' });
  }

  // Save
  const fileName = 'thumbnail-report-' + new Date().toISOString().slice(0, 10) + '.pdf';
  doc.save(fileName);
}
